### ISSUE TITLE
Failure when non-default ports are used such as jmx-manager-http-port 7199

### ISSUE THREAD

**Issue by michaelrajendran** [nyla-solutions/gedi-geode-security-extensions#5]
Following is the stack trace:
Exception in thread "main" org.apache.geode.security.GemFireSecurityException: Security check failed. required credential not provided

        at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.attemptToJoin(GMSJoinLeave.java:455)

        at org.apache.geode.distributed.internal.membership.gms.membership.GMSJoinLeave.join(GMSJoinLeave.java:339)

        at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.join(GMSMembershipManager.java:656)

        at org.apache.geode.distributed.internal.membership.gms.mgr.GMSMembershipManager.joinDistributedSystem(GMSMembershipManager.java:745)

        at org.apache.geode.distributed.internal.membership.gms.Services.start(Services.java:191)

        at org.apache.geode.distributed.internal.membership.gms.GMSMemberFactory.newMembershipManager(GMSMemberFactory.java:106)

        at org.apache.geode.distributed.internal.membership.MemberFactory.newMembershipManager(MemberFactory.java:90)

        at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:1042)

        at org.apache.geode.distributed.internal.ClusterDistributionManager.<init>(ClusterDistributionManager.java:1076)

        at org.apache.geode.distributed.internal.ClusterDistributionManager.create(ClusterDistributionManager.java:562)

        at org.apache.geode.distributed.internal.InternalDistributedSystem.initialize(InternalDistributedSystem.java:763)

        at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:355)

        at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:341)

        at org.apache.geode.distributed.internal.InternalDistributedSystem.newInstance(InternalDistributedSystem.java:335)

        at org.apache.geode.distributed.DistributedSystem.connect(DistributedSystem.java:211)

        at org.apache.geode.distributed.internal.InternalLocator.startDistributedSystem(InternalLocator.java:636)

        at org.apache.geode.distributed.internal.InternalLocator.startLocator(InternalLocator.java:311)

        at org.apache.geode.distributed.LocatorLauncher.start(LocatorLauncher.java:641)

        at org.apache.geode.distributed.LocatorLauncher.run(LocatorLauncher.java:549)

        at org.apache.geode.distributed.LocatorLauncher.main(LocatorLauncher.java:191)

**Comment by michaelrajendran** [comment]
gemfire.jmx-manager-http-port = 7199
      gemfire.jmx-manager-port = 1199
